"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";

type Story = { slug: string; title: string; subtitle: string; language: "Dayak Ngaju" | "Maanyan" | "Bakumpay"; author: string; wave: string };
const stories: Story[] = [
  { slug: "tulak-nyasap", title: "Tulak Nyasap", subtitle: "Pergi Berkebun", language: "Maanyan", author: "Desy Apriati", wave: "Gelombang 1" },
  { slug: "tandik-bagagasa", title: "Tandik Bagagasa", subtitle: "Tarian Bagagasa", language: "Bakumpay", author: "Andheny Purwasih", wave: "Gelombang 1" },
  { slug: "lomba-balanjaan", title: "Lomba Balanjaan Mensei", subtitle: "Lomba Mendayung", language: "Bakumpay", author: "Robet Domelo", wave: "Gelombang 1" },
  { slug: "dombi-je-bahalap-atei", title: "Dombi je Bahalap Atei", subtitle: "Dombi yang Baik Hati", language: "Dayak Ngaju", author: "Arie", wave: "Gelombang 2" },
  { slug: "hi-nisa-pannai-ikamit", title: "Hi Nisa Pannai Ikamit", subtitle: "Nisa Pandai Menjahit", language: "Maanyan", author: "Masnatiati", wave: "Gelombang 2" },
  { slug: "lanting-bara-batang-pisang", title: "Lanting Bara Batang Pisang", subtitle: "Rakit dari Batang Pisang", language: "Dayak Ngaju", author: "Ahmad Fakhri", wave: "Gelombang 2" },
  { slug: "odon-tuntang-tingang", title: "Odon tuntang Tingang", subtitle: "Odon dan Rangkong Badak", language: "Dayak Ngaju", author: "Harry Wahyudi", wave: "Gelombang 2" },
  { slug: "pipet-purun", title: "Pipet Purun Rumbun tuntang Rimbun", subtitle: "Sedotan Purun Rumbun dan Rimbun", language: "Dayak Ngaju", author: "Mia Cisadani", wave: "Gelombang 2" },
  { slug: "pulau-borneoku", title: "Pulau Borneoku je Tatau Haliai", subtitle: "Pulau Borneoku yang Kaya Raya", language: "Dayak Ngaju", author: "Valentina", wave: "Gelombang 2" },
];
const filters = ["Semua cerita", "Dayak Ngaju", "Maanyan", "Bakumpay"] as const;
function PlayIcon({ paused = false }: { paused?: boolean }) { return paused ? <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="5" y="4" width="5" height="16" rx="1" /><rect x="14" y="4" width="5" height="16" rx="1" /></svg> : <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M7 4.8c0-.8.9-1.3 1.6-.9l12 7.2a1 1 0 0 1 0 1.8l-12 7.2c-.7.4-1.6-.1-1.6-.9V4.8Z" /></svg>; }
function formatTime(value: number) { if (!Number.isFinite(value)) return "0:00"; return `${Math.floor(value / 60)}:${String(Math.floor(value % 60)).padStart(2, "0")}`; }

export default function Home() {
  const [filter, setFilter] = useState<(typeof filters)[number]>("Semua cerita");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState(stories[0]);
  const [playing, setPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [mobileOpen, setMobileOpen] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);
  const playerRef = useRef<HTMLDivElement>(null);
  const visible = stories.filter((story) => (filter === "Semua cerita" || story.language === filter) && `${story.title} ${story.subtitle} ${story.language}`.toLowerCase().includes(query.toLowerCase()));

  useEffect(() => { const audio = audioRef.current; if (!audio) return; audio.load(); setCurrentTime(0); setDuration(0); if (playing) audio.play().catch(() => setPlaying(false)); }, [selected.slug]); // eslint-disable-line react-hooks/exhaustive-deps
  function togglePlay() { const audio = audioRef.current; if (!audio) return; if (audio.paused) audio.play().then(() => setPlaying(true)).catch(() => setPlaying(false)); else { audio.pause(); setPlaying(false); } }
  function chooseStory(story: Story) { if (selected.slug === story.slug) togglePlay(); else { setSelected(story); setPlaying(true); } playerRef.current?.scrollIntoView({ behavior: "smooth", block: "center" }); }

  return <>
    <header className="site-header" id="utama"><div className="header-inner wrap"><a className="brand" href="#utama" aria-label="Hapakat, kembali ke utama" onClick={() => setMobileOpen(false)}><Image src="/media/logo-hapakat.png" width={175} height={48} alt="Hapakat" priority /></a><nav className={`nav ${mobileOpen ? "nav-open" : ""}`} aria-label="Navigasi utama"><a href="#utama" onClick={() => setMobileOpen(false)}>Utama</a><a href="#galeri" onClick={() => setMobileOpen(false)}>Galeri Cerita</a><a href="#cerita-pendengar" onClick={() => setMobileOpen(false)}>Cerita Pendengar</a><a href="#sukarelawan" onClick={() => setMobileOpen(false)}>Sukarelawan</a><a href="#tentang" onClick={() => setMobileOpen(false)}>Tentang</a></nav><a className="header-cta" href="#galeri">Mulai mendengar <span aria-hidden="true">↗</span></a><button className="menu-toggle" type="button" aria-label={mobileOpen ? "Tutup menu" : "Buka menu"} aria-expanded={mobileOpen} onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? "✕" : "☰"}</button></div></header>
    <main>
      <section className="hero"><div className="hero-glow" aria-hidden="true" /><div className="wrap hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> SUARA KALIMANTAN TENGAH</div><h1>Setiap cerita punya <em>suara.</em><br />Setiap suara menjaga <em>bahasa.</em></h1><p>Dengarkan cerita rakyat dalam bahasa Dayak Ngaju, Maanyan, dan Bakumpay. Temukan kisahnya, kenali bahasanya, dan teruskan tradisi lisannya.</p><div className="hero-actions"><a className="button button-primary" href="#galeri">Jelajahi cerita <span aria-hidden="true">↗</span></a><a className="text-link" href="#tentang">Kenali Hapakat <span aria-hidden="true">→</span></a></div><div className="hero-stats" aria-label="Koleksi Hapakat"><div><strong>09</strong><span>buku audio</span></div><div><strong>03</strong><span>bahasa daerah</span></div><div><strong>02</strong><span>gelombang cerita</span></div></div></div><div className="hero-art" aria-label="Sampul cerita Tulak Nyasap"><div className="hero-orbit orbit-one" aria-hidden="true" /><div className="hero-orbit orbit-two" aria-hidden="true" /><div className="hero-sun" aria-hidden="true" /><div className="hero-card hero-card-back"><Image src="/media/covers/tandik-bagagasa.jpg" alt="Sampul Tandik Bagagasa" width={440} height={310} /></div><div className="hero-card hero-card-front"><Image src="/media/covers/tulak-nyasap.jpg" alt="Sampul Tulak Nyasap" width={440} height={310} priority /></div><span className="hero-sticker">CERITA<br />DAERAH<br /><b>↗</b></span><div className="hero-caption"><span className="sound-bars" aria-hidden="true"><i /><i /><i /><i /><i /></span> Dengarkan kisah dari tanah Borneo</div></div></div></section>
      <section className="catalog-section section-pad" id="galeri"><div className="wrap"><div className="section-heading"><div><div className="section-kicker">01 / GALERI CERITA</div><h2>Cerita untuk <em>didengar.</em><br />Bahasa untuk <em>diingat.</em></h2></div><p>Jelajahi buku audio dwibahasa dari Kalimantan Tengah. Pilih cerita, dengarkan narasinya, lalu buka buku untuk mengikuti kisahnya.</p></div><div className="catalog-toolbar"><div className="filters" role="group" aria-label="Saring berdasarkan bahasa">{filters.map((item) => <button key={item} className={filter === item ? "filter active" : "filter"} type="button" aria-pressed={filter === item} onClick={() => setFilter(item)}>{item}</button>)}</div><label className="search-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8" /><path d="m16 16 5 5" /></svg><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari cerita..." aria-label="Cari cerita" /></label></div><div className="story-grid">{visible.map((story, index) => <article className="story-card" key={story.slug}><button type="button" className="cover-button" onClick={() => chooseStory(story)} aria-label={`Putar ${story.title}`}><Image src={`/media/covers/${story.slug}.jpg`} alt={`Sampul buku ${story.title}`} width={440} height={310} loading={index > 2 ? "lazy" : "eager"} /><span className="cover-play"><PlayIcon /></span></button><div className="card-meta"><span>{story.language}</span><span>{story.wave}</span></div><h3>{story.title}</h3><p>{story.subtitle}</p><div className="card-footer"><span>Oleh {story.author}</span><button type="button" onClick={() => chooseStory(story)} aria-label={`Dengarkan ${story.title}`}>↗</button></div></article>)}</div>{visible.length === 0 && <div className="empty-state">Belum ada cerita yang cocok. Coba kata kunci atau bahasa lain.</div>}</div></section>
      <section className="player-section" ref={playerRef} aria-label="Pemutar buku audio"><div className="wrap player-layout"><div className="player-cover"><Image src={`/media/covers/${selected.slug}.jpg`} alt={`Sampul ${selected.title}`} width={440} height={310} /></div><div className="player-content"><div className="section-kicker">SEDANG DIDENGARKAN · {selected.language.toUpperCase()}</div><h2>{selected.title}</h2><p>{selected.subtitle} · Oleh {selected.author}</p><audio ref={audioRef} src={`/media/audio/${selected.slug}.mp3`} preload="metadata" onTimeUpdate={(event) => setCurrentTime(event.currentTarget.currentTime)} onLoadedMetadata={(event) => setDuration(event.currentTarget.duration)} onEnded={() => setPlaying(false)} aria-label={`Buku audio ${selected.title}`} /><div className="player-controls"><button className="player-main-button" type="button" onClick={togglePlay} aria-label={playing ? "Jeda audio" : "Putar audio"}><PlayIcon paused={playing} /></button><div className="player-timeline"><input type="range" min={0} max={duration || 1} step={1} value={currentTime} aria-label="Posisi audio" onChange={(event) => { const next = Number(event.target.value); if (audioRef.current) audioRef.current.currentTime = next; setCurrentTime(next); }} style={{ background: `linear-gradient(to right, #f79431 ${(currentTime / (duration || 1)) * 100}%, #dfd2c5 0%)` }} /><div className="time-labels"><span>{formatTime(currentTime)}</span><span>{formatTime(duration)}</span></div></div></div><a className="book-link" href={`/media/books/${selected.slug}.pdf`} target="_blank" rel="noopener noreferrer">Buka buku cerita (PDF) <span aria-hidden="true">↗</span></a></div></div></section>
      <section className="listener-section section-pad" id="cerita-pendengar"><div className="wrap listener-grid"><div className="listener-art"><span className="quote-mark">“</span><div className="listener-wave" aria-hidden="true">⌁ ⌁ ⌁</div><p>Cerita hidup ketika<br />terus diceritakan.</p><span className="listener-ring ring-a" /><span className="listener-ring ring-b" /></div><div className="listener-copy"><div className="section-kicker">02 / CERITA PENDENGAR</div><h2>Dari telinga,<br /><em>turun ke hati.</em></h2><p>Setiap orang punya cerita yang dekat dengan rumah, keluarga, dan bahasa pertama mereka. Saat mendengarkan, kita ikut menjaga ingatan itu tetap hidup.</p><div className="listener-note"><span>✦</span><p>Pilih satu kisah di galeri, dengarkan bersama orang terdekat, lalu ceritakan kembali dengan kata-katamu sendiri.</p></div><a className="text-link dark" href="#galeri">Temukan cerita pilihanmu <span aria-hidden="true">→</span></a></div></div></section>
      <section className="volunteer-section section-pad" id="sukarelawan"><div className="wrap volunteer-grid"><div><div className="section-kicker">03 / SUKARELAWAN</div><h2>Bahasa terjaga<br />karena <em>kita bersama.</em></h2></div><div className="volunteer-content"><p>Hapakat tumbuh lewat kolaborasi penutur bahasa daerah, penulis, narator, penyunting, ilustrator, dan masyarakat yang ingin berbagi cerita.</p><div className="volunteer-roles"><span>Penutur & narator</span><span>Penulis cerita</span><span>Ilustrator</span><span>Penyunting</span></div><p className="volunteer-small">Ingin turut menjaga cerita daerah? Kenali karya yang sudah ada dan siapkan kisah dari lingkunganmu.</p></div></div></section>
      <section className="about-section section-pad" id="tentang"><div className="wrap about-grid"><div><div className="section-kicker">04 / TENTANG HAPAKAT</div><h2>Tradisi lisan,<br /><em>ruang digital.</em></h2></div><div className="about-copy"><p>Hapakat adalah Harmoni Aksi Pelestarian Bahasa Daerah Kalimantan Tengah: ruang belajar dan rekreasi yang menghadirkan cerita daerah dalam bentuk buku audio.</p><p>Dikembangkan sebagai krida Duta Bahasa Provinsi Kalimantan Tengah 2025, Hapakat mempertemukan suara penutur, kisah setempat, dan teknologi agar bahasa daerah lebih dekat dengan generasi muda serta masyarakat luas.</p><div className="about-languages"><span>DAYAK NGAJU</span><span>MAANYAN</span><span>BAKUMPAY</span></div></div></div></section>
    </main>
    <footer className="footer"><div className="wrap footer-top"><Image src="/media/logo-hapakat.png" alt="Hapakat" width={180} height={50} /><p>Merawat bahasa lewat cerita.<br />Kalimantan Tengah, Indonesia.</p><a href="#utama">Kembali ke atas ↑</a></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Hapakat</span><span>Harmoni Aksi Pelestarian Bahasa Daerah Kalimantan Tengah</span></div></footer>
  </>;
}
